# Generated by Django 3.2.9 on 2023-03-24 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_alter_feed_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedimage',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='feeds.feed'),
        ),
    ]
