# Generated by Django 3.2.9 on 2023-03-20 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_userprofile_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
