# Generated by Django 3.2.9 on 2023-04-10 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0003_profilecontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecontact',
            name='contact_type',
            field=models.CharField(choices=[('mail', 'Email'), ('phone', 'Phone'), ('t.me', 'Telegram'), ('vk', 'VK')], max_length=7),
        ),
        migrations.AlterField(
            model_name='profilecontact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL),
        ),
    ]
