# Generated by Django 3.2.9 on 2023-03-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_registrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiregistrator',
            name='api_name',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
