# Generated by Django 3.2.9 on 2023-02-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardskill',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='softskill',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
